version: '3.9'

services:
  web_api:
    build: ./back
    container_name: web_api
    command: >
      sh -c "
        echo 'Starting project...' &&
        cd back && alembic upgrade head &&
        python app.py
      "
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    networks:
      - menu_networks
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15.1-alpine
    container_name: db_postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - menu_networks

networks:
  menu_networks:
    name: menu_networks

volumes:
  db_data:
    name: db_data