version: '3.9'

services:
  web_api:
    build: ./back
    container_name: web_api
    command: >
      sh -c "
        echo 'Starting project...' &&
        cd back && alembic upgrade head &&
        python app.py
      "
    volumes:
      - .:/app
      - celery-data:/app/task_files
    ports:
      - '8000:8000'
    networks:
      - menu_networks
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  db:
    image: postgres:15.1-alpine
    container_name: db_postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - menu_networks

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    restart: always
    networks:
      - menu_networks
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11.8-alpine
    env_file:
      - .env
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - 5672:5672
    networks:
      - menu_networks

  celery:
    container_name: "celery"
    build: ./back
    entrypoint: >
      sh -c "
        celery -A api.celery_app:celery_app worker --loglevel=INFO
      "
    env_file:
      - .env
    networks:
      - menu_networks
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - celery-data:/app/task_files

networks:
  menu_networks:
    name: menu_networks

volumes:
  db_data:
    name: db_data
  celery-data:
    name: celery-data
