version: '3.9'

services:
  test_web_api:
    build: ./back
    container_name: test_web_api
    command: "pytest -v"
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    networks:
      - test_menu_networks
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15.1-alpine
    container_name: test_db_postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_TEST}
    # volumes:
    #   - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - test_menu_networks

networks:
  test_menu_networks:
    name: test_menu_networks