"""empty message

Revision ID: cda627c66ae9
Revises:
Create Date: 2023-01-17 22:14:18.154082

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cda627c66ae9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "menu",
        sa.Column(
            "id",
            sa.Integer(),
            sa.Identity(
                always=True,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column(
            "description",
            sa.String(
                length=256,
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_menu_title"), "menu", ["title"], unique=True)
    op.create_table(
        "submenu",
        sa.Column(
            "id",
            sa.Integer(),
            sa.Identity(
                always=True,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column(
            "description",
            sa.String(
                length=256,
            ),
            nullable=True,
        ),
        sa.Column("menu_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["menu_id"],
            ["menu.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_submenu_title"),
        "submenu",
        ["title"],
        unique=True,
    )
    op.create_table(
        "dich",
        sa.Column(
            "id",
            sa.Integer(),
            sa.Identity(
                always=True,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column(
            "description",
            sa.String(
                length=256,
            ),
            nullable=True,
        ),
        sa.Column(
            "price",
            sa.Numeric(
                precision=10,
                scale=2,
            ),
            nullable=True,
        ),
        sa.Column("submenu_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["submenu_id"],
            ["submenu.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dich_price"), "dich", ["price"], unique=False)
    op.create_index(op.f("ix_dich_title"), "dich", ["title"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dich_title"), table_name="dich")
    op.drop_index(op.f("ix_dich_price"), table_name="dich")
    op.drop_table("dich")
    op.drop_index(op.f("ix_submenu_title"), table_name="submenu")
    op.drop_table("submenu")
    op.drop_index(op.f("ix_menu_title"), table_name="menu")
    op.drop_table("menu")
    # ### end Alembic commands ###
